countries = [
    "Argentina",
    "France",
    "Brazil",
    "Belgium",
    "England",
    "Netherlands",
    "Croatia",
    "Italy",
    "Portugal",
    "Spain",
    "Morocco",
    "Switzerland",
    "USA",
    "Germany",
    "Mexico",
    "Uruguay",
    "Colombia",
    "Senegal",
    "Denmark",
    "Japan",
    "Peru",
    "Sweden",
    "Poland",
    "IR Iran",
    "Serbia",
    "Wales",
    "Korea Republic",
    "Tunisia",
    "Australia",
    "Ukraine",
    "Chile",
    "Austria",
    "Hungary",
    "Algeria",
    "Egypt",
    "Scotland",
    "Russia",
    "Czech Republic",
    "Costa Rica",
    "Nigeria",
    "Ecuador",
    "Cameroon",
    "Türkiye",
    "Norway",
    "Ivory Coast",
    "Romania",
    "Canada",
    "Paraguay",
    "Ireland",
    "Burkina Faso",
    "Slovakia",
    "Greece",
    "Mali",
    "Saudi Arabia",
    "Venezuela",
    "Finland",
    "Bosnia and Herzegovina",
    "Panama",
    "Slovenia",
    "Ghana",
    "Qatar",
    "Northern Ireland",
    "Jamaica",
    "Iceland",
    "North Macedonia",
    "South Africa",
    "Iraq",
    "Albania",
    "Montenegro",
    "Congo DR",
    "Cabo Verde",
    "United Arab Emirates",
    "Oman",
    "Uzbekistan",
    "El Salvador",
    "Bulgaria",
    "Georgia",
    "Israel",
    "Guinea",
    "Honduras",
    "China",
    "Gabon",
    "Bolivia",
    "Jordan",
    "Bahrain",
    "Zambia",
    "Haiti",
    "Curaçao",
    "Uganda",
    "Syria",
    "Luxembourg",
    "Benin",
    "Palestine",
    "Equatorial Guinea",
    "Vietnam",
    "Kyrgyz Republic",
    "Armenia",
    "Belarus",
    "Lebanon",
    "New Zealand",
    "India",
    "Kenya",
    "Congo",
    "Trinidad and Tobago",
    "Mauritania",
    "Namibia",
    "Kosovo",
    "Estonia",
    "Tajikistan",
    "Madagascar",
    "Cyprus",
    "Kazakhstan",
    "Guinea-Bissau",
    "Thailand",
    "Korea DPR",
    "Guatemala",
    "Sierra Leone",
    "Angola",
    "Mozambique",
    "The Gambia",
    "Libya",
    "Central African",
    "Niger",
    "Azerbaijan",
    "Faroe Islands",
    "Zimbabwe",
    "Malawi",
    "Sudan",
    "Togo",
    "Tanzania",
    "Comoros",
    "Latvia",
    "Antigua and Barbuda",
    "Solomon Islands",
    "Rwanda",
    "Philippines",
    "Turkmenistan",
    "Malaysia",
    "St Kitts and Nevis",
    "Nicaragua",
    "Suriname",
    "Ethiopia",
    "Kuwait",
    "Eswatini",
    "Burundi",
    "Lithuania",
    "Hong Kong",
    "Liberia",
    "Indonesia",
    "Lesotho",
    "Dominican Republic",
    "Botswana",
    "Andorra",
    "Maldives",
    "Afghanistan",
    "Chinese Taipei",
    "Yemen",
    "Singapore",
    "Papua New Guinea",
    "Myanmar",
    "New Caledonia",
    "Tahiti",
    "South Sudan",
    "Vanuatu",
    "Cuba",
    "Puerto Rico",
    "Barbados",
    "Fiji",
    "St Lucia",
    "Guyana",
    "Moldova",
    "Malta",
    "Bermuda",
    "Nepal",
    "Grenada",
    "Cambodia",
    "Belize",
    "St Vincent and the Grenadines",
    "Montserrat",
    "Mauritius",
    "Chad",
    "Macau",
    "Mongolia",
    "São Tomé and Príncipe",
    "Bhutan",
    "Dominica",
    "American Samoa",
    "Laos",
    "Cook Islands",
    "Samoa",
    "Brunei Darussalam",
    "Bangladesh",
    "Djibouti",
    "Tonga",
    "Pakistan",
    "Timor-Leste",
    "Seychelles",
    "Cayman Islands",
    "Liechtenstein",
    "Eritrea",
    "Gibraltar",
    "Somalia",
    "Bahamas",
    "Aruba",
    "Turks and Caicos Islands",
    "Guam",
    "Sri Lanka",
    "US Virgin Islands",
    "British Virgin Islands",
    "Anguilla",
    "San Marino",
    "Uefa",
    "Concacaf",
    "Fifa",
    "Conmebol",
    "Uafa"
]